-- قاعدة بيانات أولية لتطبيق الدردشة العربية
create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username varchar(4) unique not null,
  display_name text not null,
  avatar_url text,
  coins integer not null default 0,
  plus_active boolean not null default false,
  is_admin boolean not null default false,
  is_banned boolean not null default false,
  is_online boolean not null default false,
  created_at timestamptz not null default now(),
  constraint username_len check (char_length(username) between 1 and 4)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  body text,
  message_type text not null default 'text',
  media_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.groups (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  is_private boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.group_members (
  group_id uuid not null references public.groups(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  is_banned boolean not null default false,
  joined_at timestamptz not null default now(),
  primary key(group_id, user_id)
);

create table if not exists public.gifts (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  coins_price integer not null,
  receiver_coins integer not null,
  active boolean not null default true
);

create table if not exists public.payment_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  package_type text not null,
  amount_usd numeric(10,2) not null,
  transaction_reference text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  target_user_id uuid references public.profiles(id) on delete cascade,
  target_url text,
  reason text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.messages enable row level security;
alter table public.groups enable row level security;
alter table public.group_members enable row level security;
alter table public.payment_requests enable row level security;
alter table public.reports enable row level security;

-- هذه سياسات MVP. قبل الإطلاق العام يجب مراجعتها بدقة مع صلاحيات المشرف.
create policy "profiles readable"
on public.profiles for select
to authenticated using (is_banned = false);

create policy "own profile insert"
on public.profiles for insert
to authenticated with check (id = auth.uid());

create policy "own profile update"
on public.profiles for update
to authenticated using (id = auth.uid());

create policy "messages participants read"
on public.messages for select
to authenticated using (sender_id = auth.uid() or receiver_id = auth.uid());

create policy "messages sender insert"
on public.messages for insert
to authenticated with check (sender_id = auth.uid());

create policy "groups members read"
on public.group_members for select
to authenticated using (user_id = auth.uid());

create policy "payment own insert"
on public.payment_requests for insert
to authenticated with check (user_id = auth.uid());

create policy "payment own read"
on public.payment_requests for select
to authenticated using (user_id = auth.uid());

create policy "reports own insert"
on public.reports for insert
to authenticated with check (reporter_id = auth.uid());
